# Copyright (c) 2025 Rockchip Electronics Co. Ltd.
# Author: Xing Zheng <zhengxing@rock-chips.com>

pcm.!default
{
    type asym
    playback.pcm "hw:0,0"
    capture.pcm "multi_cap2"
}

pcm.multi_cap2 {
    type multi
    slaves.a.pcm "hw:0,0,0"
    slaves.b.pcm "hw:7,1,0"
    slaves.a.channels 2
    slaves.b.channels 2
    bindings.0.slave a
    bindings.0.channel 1
    bindings.1.slave b
    bindings.1.channel 0
}

